(() => {
const DB='#0e1d2a', DT='#f4f4f4', ACC='#52a4d5', TAG='assets/tag-leme-branca.png?v=111.4', HLOGO='assets/logo-leme-manuscrita-escura.png?v=111.4';
const DARK={'twitter-text-dark':'twitter-text','twitter-image-dark':'twitter-image','twitter-two-images-dark':'twitter-two-images','handwritten-dark':'handwritten'};
Object.assign(LEME_ART_TEMPLATES,{'twitter-text-dark':'Twitter Texto · Escuro','twitter-image-dark':'Twitter Texto + imagem · Escuro','twitter-two-images-dark':'Twitter Texto + 2 imagens · Escuro','handwritten-dark':'Texto manuscrito · Escuro'});
Object.keys(DARK).forEach(k=>LEME_ART_BASE_FONT_SIZES[k]=LEME_ART_BASE_FONT_SIZES[DARK[k]]);
const base=t=>DARK[t]||t, dark=t=>!!DARK[t], keys=s=>s==='secondary'?{d:'image2DataUrl',n:'image2Name',e:'image2Element',t:'image2MediaType',a:'video2AudioEnabled',x:'image2PositionX',y:'image2PositionY',s:'image2TrimStart',f:'image2TrimEnd'}:{d:'imageDataUrl',n:'imageName',e:'imageElement',t:'imageMediaType',a:'videoAudioEnabled',x:'imagePositionX',y:'imagePositionY',s:'imageTrimStart',f:'imageTrimEnd'};
const isVid=(u,t='')=>String(t).toLowerCase()==='video'||/^data:video\//i.test(String(u||''))||/^\/media\/leme-art\//.test(String(u||''))||/\.(mp4|webm|mov)(\?|$)/i.test(String(u||''));
const clamp=(v,a,b)=>Math.min(b,Math.max(a,Number.isFinite(Number(v))?Number(v):a));
function enhance(d,s={}){if(!d)return d;['imageTrimStart','imageTrimEnd','image2TrimStart','image2TrimEnd'].forEach(k=>d[k]=Math.max(0,Number(s[k]??d[k]??0)||0));d.highlightColor=d.highlightColor||ACC;return d;}
const c0=createLemeArtDraft;createLemeArtDraft=function(d={},f={}){return enhance(c0(d,f),d)};
const g0=getLemeArtDraft;getLemeArtDraft=function(s='page'){return enhance(g0(s))};
const p0=prepareLemeArtModalDraft;prepareLemeArtModalDraft=function(p=null){const d=enhance(p0(p),p||{});if(p){d.imageTrimStart=Number(p.arte_video_inicio??d.imageTrimStart)||0;d.imageTrimEnd=Number(p.arte_video_fim??d.imageTrimEnd)||0;d.image2TrimStart=Number(p.arte_video2_inicio??d.image2TrimStart)||0;d.image2TrimEnd=Number(p.arte_video2_fim??d.image2TrimEnd)||0;}return d};
const s0=serializeLemeArtCarouselSlides;serializeLemeArtCarouselSlides=function(sc='modal-carousel'){const c=getLemeArtCarousel(sc);return s0(sc).map((o,i)=>{const d=enhance(c.slides[i]||{});return {...o,imageTrimStart:d.imageTrimStart||0,imageTrimEnd:d.imageTrimEnd||0,image2TrimStart:d.image2TrimStart||0,image2TrimEnd:d.image2TrimEnd||0}})};
const cp0=collectPost;collectPost=function(){const r=cp0();if(String(r.cliente_id)!==LEME_CLIENT_ID)return r;const d=getLemeArtDraft('modal');return {...r,arte_video_inicio:d.imageTrimStart||0,arte_video_fim:d.imageTrimEnd||0,arte_video2_inicio:d.image2TrimStart||0,arte_video2_fim:d.image2TrimEnd||0,arte_slides:serializeLemeArtCarouselSlides('modal-carousel')}};
function range(d,sl,v){const k=keys(sl),du=Number(v?.duration||0),m=du>0?du:100,s=clamp(d[k.s]||0,0,m);let f=Number(d[k.f]||0);if(!f)f=du||m;f=clamp(f,0,m);if(f<=s+.05)f=Math.min(m,s+.1);return {du,m,s,f};}
function fmt(v){v=Math.max(0,Number(v)||0);const m=Math.floor(v/60),s=v-m*60;return m?`${m}:${s.toFixed(1).padStart(4,'0')}`:`${s.toFixed(1)}s`;}
function trimHTML(sc,ck,sl){const p=`leme_art_${sc}_${ck}`;return `<div id="${p}_trim_box" class="leme-art-trim-box hidden"><button class="btn secondary small" type="button" onclick="document.getElementById('${p}_trim_panel').classList.toggle('hidden')">✂ Cortar vídeo</button><div id="${p}_trim_panel" class="leme-art-trim-panel hidden"><label>Começo <b id="${p}_trim_sl">0.0s</b><input id="${p}_trim_s" type="range" min="0" max="100" step="0.05" oninput="setLemeTrim('${sc}','${sl}','s',this.value)"></label><label>Final <b id="${p}_trim_fl">0.0s</b><input id="${p}_trim_f" type="range" min="0.1" max="100" step="0.05" oninput="setLemeTrim('${sc}','${sl}','f',this.value)"></label><small id="${p}_trim_sum"></small></div></div>`}
const dz0=renderLemeArtImageDropzone;renderLemeArtImageDropzone=function(sc,ck,sl,l,t,d){let h=dz0(sc,ck,sl,l,t,d),b=trimHTML(sc,ck,sl),m='<button class="leme-art-clear-image';return h.includes(m)?h.replace(m,b+m):h+b};
window.setLemeTrim=function(sc,sl,e,v){const d=getLemeArtDraft(sc),k=keys(sl),r=range(d,sl,d[k.e]);if(e==='s')d[k.s]=clamp(v,0,Math.max(0,r.f-.1));else d[k.f]=clamp(v,r.s+.1,r.m);applyTrim(sc,sl);syncTrim(sc);scheduleLemeArtPreview(sc)};
function applyTrim(sc,sl){const d=getLemeArtDraft(sc),k=keys(sl),v=d[k.e];if(!v||v.tagName!=='VIDEO')return;const r=range(d,sl,v);v.__lemeTrimStart=r.s;v.__lemeTrimEnd=r.f;if(!v.__lemeTrim){v.addEventListener('timeupdate',()=>{if(v.__lemeTrimEnd>v.__lemeTrimStart&&v.currentTime>=v.__lemeTrimEnd-.02)try{v.currentTime=v.__lemeTrimStart}catch{}});v.__lemeTrim=1;}if(v.currentTime<r.s||v.currentTime>=r.f)try{v.currentTime=r.s}catch{};v.play().catch(()=>{})}
function syncTrim(sc){const d=getLemeArtDraft(sc),arr=[['single','primary'],['left','primary'],['right','secondary'],['gradient','primary']];for(const[ck,sl]of arr){const p=`leme_art_${sc}_${ck}`,b=document.getElementById(`${p}_trim_box`);if(!b)continue;const k=keys(sl),show=!!d[k.d]&&isVid(d[k.d],d[k.t]);b.classList.toggle('hidden',!show);if(!show)continue;const r=range(d,sl,d[k.e]),si=document.getElementById(`${p}_trim_s`),fi=document.getElementById(`${p}_trim_f`);if(si){si.max=r.m;si.value=r.s}if(fi){fi.max=r.m;fi.value=r.f}document.getElementById(`${p}_trim_sl`)?.replaceChildren(document.createTextNode(fmt(r.s)));document.getElementById(`${p}_trim_fl`)?.replaceChildren(document.createTextNode(fmt(r.f)));document.getElementById(`${p}_trim_sum`)?.replaceChildren(document.createTextNode(`Trecho final: ${fmt(r.f-r.s)}`));}}
function darkGroups(sc){const d=getLemeArtDraft(sc),b=base(d.template),p=`leme_art_${sc}`;if(dark(d.template)){document.getElementById(`${p}_image_group`)?.classList.toggle('hidden',b!=='twitter-image');document.getElementById(`${p}_two_image_group`)?.classList.toggle('hidden',b!=='twitter-two-images')}syncTrim(sc)}
const se0=setLemeArtTemplate;setLemeArtTemplate=function(sc,v){const r=se0(sc,v);darkGroups(sc);return r};window.setLemeArtTemplate=setLemeArtTemplate;
const sy0=syncLemeArtImageControls;syncLemeArtImageControls=function(sc='page'){const r=sy0(sc);darkGroups(sc);return r};
// Corrige upload de vídeo especificamente dentro dos cards/modais sem rerenderizar toda a tela.
const rf0=readLemeArtImageFile;readLemeArtImageFile=function(file,sc,sl='primary',tpl='twitter-image'){if(!String(file?.type||'').startsWith('video/')||!String(sc).startsWith('modal'))return rf0(file,sc,sl,tpl);if(Number(file.size||0)>8*1024*1024)return toast('Use vídeos de até 8 MB por arquivo.');const rd=new FileReader();rd.onload=()=>{const d=getLemeArtDraft(sc),k=keys(sl);d[k.d]=String(rd.result||'');d[k.n]=file.name||'Vídeo selecionado';d[k.e]=null;d[k.t]='video';d[k.a]=true;d[k.s]=0;d[k.f]=0;if(sl==='secondary'){d.image2PositionX=50;d.image2PositionY=50}else{d.imagePositionX=50;d.imagePositionY=50}d.template=normalizeLemeArtTemplate(tpl);const sel=document.getElementById(`leme_art_${sc}_template`);if(sel)sel.value=d.template;syncLemeArtFontControls(sc);syncLemeArtImageControls(sc);scheduleLemeArtPreview(sc);startLoop();toast('Vídeo adicionado ao card. Ajuste posição, áudio e corte.');};rd.onerror=()=>toast('Não foi possível abrir o vídeo.');rd.readAsDataURL(file)};
const gi0=getLemeArtUserImage;getLemeArtUserImage=async function(d,sl='primary'){const v=await gi0(d,sl);if(v?.tagName==='VIDEO'){const r=range(d,sl,v);v.__lemeTrimStart=r.s;v.__lemeTrimEnd=r.f;if(v.currentTime<r.s||v.currentTime>=r.f)try{v.currentTime=r.s}catch{}}return v};
let tp,hp;const lt=()=>tp||(tp=loadLemeArtImageSource(TAG)),lh=()=>hp||(hp=loadLemeArtImageSource(HLOGO));
const rd0=renderLemeArtDraftCanvas;renderLemeArtDraftCanvas=async function(d,f=d?.format,c=null){enhance(d);if(!dark(d?.template))return rd0(d,f,c);const cv=c||document.createElement('canvas'),fm=getLemeArtFormatConfig(f);cv.width=fm.width;cv.height=fm.height;const x=cv.getContext('2d');if(!x)return null;x.fillStyle=DB;x.fillRect(0,0,fm.width,fm.height);const tx=normalizeLemeArtText(d.text)||'Digite a frase que será transformada em arte.',ac=d.highlightColor||ACC,b=base(d.template);if(b==='handwritten'){const sx=Math.max(128,fm.safeMarginX),sy=Math.max(128,fm.safeMarginY),lay=fitLemeArtText(x,tx,{fontFamily:'"Elegant Bloom", "Segoe Print", cursive',fontWeight:'400',maxWidth:fm.width-sx*2,maxHeight:fm.height-sy*2-100,maxFontSize:getLemeArtMaxFontSize(d.template,d.fontScale),lineHeightRatio:1.32}),old=window.__lemeV1104Color;window.__lemeV1104Color=ac;drawLemeArtText(x,lay,fm.width/2,(fm.height-lay.height)/2,{color:DT,align:'center',circleColor:ac,highlightColor:ac,underlineColor:DT});window.__lemeV1104Color=old;try{const im=await lh(),w=Math.min(184,fm.width-120),h=Math.round(w*(im.naturalHeight||im.height)/(im.naturalWidth||im.width));x.globalAlpha=1;x.drawImage(im,(fm.width-w)/2,fm.height-60-h,w,h)}catch{}return cv}let tag=null;try{tag=await lt()}catch{}const ob=LEME_ART_CONFIG.background,ot=LEME_ART_CONFIG.textColor,oa=LEME_ART_CONFIG.accentColor,oh=window.__lemeV1104Color;LEME_ART_CONFIG.background=DB;LEME_ART_CONFIG.textColor=DT;LEME_ART_CONFIG.accentColor=ac;window.__lemeV1104Color=ac;try{if(b==='twitter-two-images'){const ms=await Promise.all([getLemeArtUserImage(d,'primary').catch(()=>null),getLemeArtUserImage(d,'secondary').catch(()=>null)]);drawLemeArtTwitterText(x,tx,tag,'two',ms,fm,d.fontScale)}else if(b==='twitter-image'){drawLemeArtTwitterText(x,tx,tag,'single',[await getLemeArtUserImage(d,'primary').catch(()=>null)],fm,d.fontScale)}else drawLemeArtTwitterText(x,tx,tag,'none',[],fm,d.fontScale)}finally{LEME_ART_CONFIG.background=ob;LEME_ART_CONFIG.textColor=ot;LEME_ART_CONFIG.accentColor=oa;window.__lemeV1104Color=oh}return cv};
const vd0=validateLemeArtDraft;validateLemeArtDraft=function(d,n=null){if(!dark(d?.template))return vd0(d,n);const l=n?`O slide ${n}`:'A arte',b=base(d.template);if(!normalizeLemeArtText(d.text))return`${l} está sem texto.`;if(b==='twitter-image'&&!d.imageDataUrl)return`${l} precisa de uma mídia.`;if(b==='twitter-two-images'&&(!d.imageDataUrl||!d.image2DataUrl))return`${l} precisa das mídias da esquerda e da direita.`;return''};
let looping=0;async function loop(){let y=0;for(const sc of['page','page-carousel','modal','modal-carousel']){if(!document.getElementById(`leme_art_${sc}_canvas`))continue;const d=getLemeArtDraft(sc);if(!((d.imageDataUrl&&isVid(d.imageDataUrl,d.imageMediaType))||(d.image2DataUrl&&isVid(d.image2DataUrl,d.image2MediaType))))continue;y=1;applyTrim(sc,'primary');applyTrim(sc,'secondary');try{await renderLemeArtCanvas(sc)}catch{}}if(!y){looping=0;return}requestAnimationFrame(loop)}function startLoop(){if(looping)return;looping=1;requestAnimationFrame(loop)}
const in0=initializeLemeArtCanvases;initializeLemeArtCanvases=function(){const r=in0();document.querySelectorAll('[data-leme-art-editor]').forEach(e=>{const sc=e.dataset.lemeArtEditor||'page';darkGroups(sc);syncTrim(sc)});startLoop();return r};
const st=document.createElement('style');st.textContent='.leme-art-trim-box{margin-top:10px;padding:11px;border:1px solid rgba(120,140,155,.25);border-radius:14px;background:rgba(82,164,213,.05)}.leme-art-trim-box.hidden,.leme-art-trim-panel.hidden{display:none!important}.leme-art-trim-panel{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px}.leme-art-trim-panel label{display:grid;gap:5px;font-size:12px}.leme-art-trim-panel input{width:100%}.leme-art-trim-panel small{grid-column:1/-1;color:var(--muted,#68747d)}';document.head.appendChild(st);
})();
