(() => {
  const V='112.1', HAND='handwritten-media', GRAD='gradient-photo', REELS='reels-box';
  const clamp=(v,a,b)=>Math.min(b,Math.max(a,Number.isFinite(Number(v))?Number(v):a));
  const inferDark=t=>/-dark$/i.test(String(t||''));
  const groupOf=t=>t===GRAD?'gradient':t===REELS?'reels':(t===HAND||String(t||'').startsWith('handwritten'))?'handwritten':'twitter';
  const countOf=d=>d.template===HAND?(String(d.handwrittenMediaMode||'').toLowerCase()==='two'?2:1):String(d.template||'').includes('two-images')?2:String(d.template||'').includes('image')||d.template===GRAD?1:0;
  const asBool=(v,fb=false)=>typeof v==='boolean'?v:(v==null||v===''?fb:['1','true','sim','yes','dark','escuro'].includes(String(v).toLowerCase()));

  function enhance(d,s={}){
    if(!d||typeof d!=='object')return d;
    const explicit=s.artDarkMode??s.arte_modo_escuro;
    if(explicit!==undefined&&explicit!==null&&explicit!=='')d.artDarkMode=asBool(explicit);
    else if(d.artDarkMode==null)d.artDarkMode=inferDark(d.template);
    if(d.template!==HAND)d.artDarkMode=inferDark(d.template);
    return d;
  }
  function state(d){d=enhance(d||{});const group=groupOf(d.template);return{group,media:countOf(d),dark:group==='gradient'||group==='reels'?false:(d.template===HAND?!!d.artDarkMode:inferDark(d.template))};}
  function target(group,media,dark){media=clamp(media,0,2);if(group==='gradient')return GRAD;if(group==='handwritten')return media?HAND:(dark?'handwritten-dark':'handwritten');if(media===2)return dark?'twitter-two-images-dark':'twitter-two-images';if(media===1)return dark?'twitter-image-dark':'twitter-image';return dark?'twitter-text-dark':'twitter-text';}

  const c0=createLemeArtDraft;createLemeArtDraft=function(data={},defs={}){return enhance(c0(data,defs),data)};
  const g0=getLemeArtDraft;getLemeArtDraft=function(scope='page'){return enhance(g0(scope))};
  const p0=prepareLemeArtModalDraft;prepareLemeArtModalDraft=function(post=null){return enhance(p0(post),post||{})};
  const s0=serializeLemeArtCarouselSlides;serializeLemeArtCarouselSlides=function(scope='modal-carousel'){const src=getLemeArtCarousel(scope)?.slides||[];return s0(scope).map((o,i)=>({...o,artDarkMode:state(enhance(src[i]||{},o)).dark}))};
  const cp0=collectPost;collectPost=function(){const r=cp0();if(String(r?.cliente_id||'')!==String(LEME_CLIENT_ID||'leme-interno'))return r;return{...r,arte_modo_escuro:state(getLemeArtDraft('modal')).dark,arte_slides:serializeLemeArtCarouselSlides('modal-carousel')}};

  function fields(scope){const s=state(getLemeArtDraft(scope));if(s.group==='reels')return `<label>Modelo da arte<select class="select" disabled><option>Reels</option></select></label>`;const grad=s.group==='gradient';return `
    <label>Modelo da arte<select class="select" id="leme_art_${scope}_v1121_group" onchange="setLemeArtModelV1121('${escapeAttr(scope)}','group',this.value)"><option value="twitter" ${s.group==='twitter'?'selected':''}>Twitter</option><option value="handwritten" ${s.group==='handwritten'?'selected':''}>Manuscrito</option><option value="gradient" ${grad?'selected':''}>Foto + Gradiente</option></select></label>
    <label>Composição<select class="select" id="leme_art_${scope}_v1121_media" ${grad?'disabled':''} onchange="setLemeArtModelV1121('${escapeAttr(scope)}','media',this.value)">${grad?'<option value="1">Imagem de fundo</option>':`<option value="0" ${s.media===0?'selected':''}>Só texto</option><option value="1" ${s.media===1?'selected':''}>Texto + 1 imagem</option><option value="2" ${s.media===2?'selected':''}>Texto + 2 imagens</option>`}</select></label>
    <label>Aparência<select class="select" id="leme_art_${scope}_v1121_dark" ${grad?'disabled':''} onchange="setLemeArtModelV1121('${escapeAttr(scope)}','dark',this.value)">${grad?'<option value="0">Padrão</option>':`<option value="0" ${!s.dark?'selected':''}>Claro</option><option value="1" ${s.dark?'selected':''}>Escuro</option>`}</select></label>`;}

  function mediaCard(scope,d,slot,label){const sec=slot==='secondary',src=String(sec?d.image2DataUrl:d.imageDataUrl||'');if(!src)return'';const x=clamp(sec?d.image2PositionX:d.imagePositionX,0,100),y=clamp(sec?d.image2PositionY:d.imagePositionY,0,100),z=clamp(sec?d.image2Zoom:d.imageZoom,5,300),id=`leme_art_${scope}_v1121_${slot}`;return `<div class="leme-v1121-media-card"><div class="leme-v1121-media-head"><div><strong>${escapeHtml(label)}</strong><small>Enquadramento dentro da moldura</small></div><button class="btn secondary small" type="button" onclick="resetLemeHandMediaV1121('${escapeAttr(scope)}','${slot}')">Centralizar</button></div><div class="leme-v1121-media-grid"><label>Horizontal <span id="${id}_x_value">${Math.round(x)}%</span><input type="range" min="0" max="100" value="${x}" oninput="setLemeHandMediaV1121('${escapeAttr(scope)}','${slot}','x',this.value)"></label><label>Vertical <span id="${id}_y_value">${Math.round(y)}%</span><input type="range" min="0" max="100" value="${y}" oninput="setLemeHandMediaV1121('${escapeAttr(scope)}','${slot}','y',this.value)"></label><label class="zoom">Zoom <span id="${id}_zoom_value">${Math.round(z)}%</span><input type="range" min="5" max="300" value="${z}" oninput="setLemeHandMediaV1121('${escapeAttr(scope)}','${slot}','zoom',this.value)"></label></div></div>`;}
  function mediaControls(scope){const d=getLemeArtDraft(scope),s=state(d);if(s.group!=='handwritten'||!s.media)return'';const cards=[mediaCard(scope,d,'primary',s.media===2?'Imagem da esquerda':'Imagem')];if(s.media===2)cards.push(mediaCard(scope,d,'secondary','Imagem da direita'));const html=cards.filter(Boolean).join('');return html?`<div class="leme-v1121-media-controls"><div><strong>Posicionar mídia</strong><small>Zoom, horizontal e vertical para cada imagem.</small></div>${html}</div>`:'<div class="leme-v1121-media-empty">Adicione uma imagem para liberar zoom e posicionamento.</div>';}

  function refresh(scope){const d=getLemeArtDraft(scope),s=state(d),ed=[...document.querySelectorAll('[data-leme-art-editor]')].find(e=>String(e.dataset.lemeArtEditor||'')===String(scope));if(ed)ed.dataset.lemeV1121Family=s.group;const q=id=>document.getElementById(`leme_art_${scope}_v1121_${id}`),a=q('group'),b=q('media'),c=q('dark');if(a)a.value=s.group;if(b){b.disabled=s.group==='gradient';if(!b.disabled)b.value=String(s.media)}if(c){c.disabled=s.group==='gradient';if(!c.disabled)c.value=s.dark?'1':'0'}const host=q('media_controls');if(host)host.innerHTML=mediaControls(scope);}

  window.setLemeArtModelV1121=function(scope,key,value){const d=getLemeArtDraft(scope),s=state(d);let group=s.group==='reels'?'twitter':s.group,media=s.media,dark=s.dark;if(key==='group')group=['twitter','handwritten','gradient'].includes(value)?value:'twitter';if(key==='media')media=clamp(value,0,2);if(key==='dark')dark=String(value)==='1';if(group==='gradient'){media=1;dark=false}d.artDarkMode=dark;if(group==='handwritten'&&media)d.handwrittenMediaMode=media===2?'two':'single';setLemeArtTemplate(scope,target(group,media,dark));const n=getLemeArtDraft(scope);n.artDarkMode=dark;if(group==='handwritten'&&media)n.handwrittenMediaMode=media===2?'two':'single';try{syncLemeArtImageControls(scope)}catch{};try{window.refreshLemeArtZoomControls?.(scope)}catch{};requestAnimationFrame(()=>refresh(scope));scheduleLemeArtPreview(scope)};

  window.setLemeHandMediaV1121=function(scope,slot,axis,value){const sec=slot==='secondary',d=getLemeArtDraft(scope),id=`leme_art_${scope}_v1121_${slot}_${axis}_value`;if(axis==='zoom'){const v=clamp(value,5,300);if(typeof window.setLemeArtMediaZoom==='function')window.setLemeArtMediaZoom(scope,slot,v);else d[sec?'image2Zoom':'imageZoom']=v;const el=document.getElementById(id);if(el)el.textContent=`${Math.round(v)}%`}else{const v=clamp(value,0,100);if(typeof window.setLemeArtImagePosition==='function')window.setLemeArtImagePosition(scope,slot,axis,v);else d[sec?(axis==='y'?'image2PositionY':'image2PositionX'):(axis==='y'?'imagePositionY':'imagePositionX')]=v;const el=document.getElementById(id);if(el)el.textContent=`${Math.round(v)}%`}scheduleLemeArtPreview(scope)};
  window.resetLemeHandMediaV1121=function(scope,slot){setLemeHandMediaV1121(scope,slot,'x',50);setLemeHandMediaV1121(scope,slot,'y',50);setLemeHandMediaV1121(scope,slot,'zoom',100);requestAnimationFrame(()=>refresh(scope))};

  const e0=renderLemeArtEditor;renderLemeArtEditor=function(scope='page',options={}){let html=e0(scope,options),s=state(getLemeArtDraft(scope));html=html.replace(/<label>Modelo da arte[\s\S]*?<\/label>/,fields(scope));html=html.replace(`data-leme-art-editor="${escapeAttr(scope)}"`,`data-leme-art-editor="${escapeAttr(scope)}" data-leme-v1121-family="${escapeAttr(s.group)}"`);html=html.replace('<div class="leme-art-actions">',`<div id="leme_art_${scope}_v1121_media_controls">${mediaControls(scope)}</div><div class="leme-art-actions">`);return html};window.renderLemeArtEditor=renderLemeArtEditor;
  const t0=setLemeArtTemplate;setLemeArtTemplate=function(scope,value){const r=t0(scope,value),d=getLemeArtDraft(scope);if(value!==HAND)d.artDarkMode=inferDark(value);requestAnimationFrame(()=>refresh(scope));return r};window.setLemeArtTemplate=setLemeArtTemplate;
  const sy0=window.syncLemeArtImageControls||syncLemeArtImageControls;window.syncLemeArtImageControls=function(scope='page'){const r=sy0(scope);requestAnimationFrame(()=>refresh(scope));return r};syncLemeArtImageControls=window.syncLemeArtImageControls;
  const i0=initializeLemeArtCanvases;initializeLemeArtCanvases=function(){const r=i0();document.querySelectorAll('[data-leme-art-editor]').forEach(e=>refresh(e.dataset.lemeArtEditor||'page'));return r};window.initializeLemeArtCanvases=initializeLemeArtCanvases;

  let logoP=null;const darkLogo=()=>logoP||(logoP=loadLemeArtImageSource('assets/logo-leme-manuscrita-escura.png?v=111.4').catch(e=>{logoP=null;throw e}));
  async function darkHand(d,f,canvas){const fm=getLemeArtFormatConfig(f),ctx=canvas.getContext('2d');if(!ctx)return canvas;ctx.clearRect(0,0,fm.width,fm.height);ctx.fillStyle='#0e1d2a';ctx.fillRect(0,0,fm.width,fm.height);const sx=Math.max(104,fm.safeMarginX),sy=Math.max(104,fm.safeMarginY),cw=fm.width-sx*2,ih=Math.min(fm.key==='story'?610:470,Math.max(250,fm.height*.38)),iy=fm.height-sy-110-ih,tb=iy-42,txt=normalizeLemeArtText(d.text)||'Digite a frase que será transformada em arte.',lay=fitLemeArtText(ctx,txt,{fontFamily:'Poppins, Arial, sans-serif',fontWeight:'400',maxWidth:cw,maxHeight:Math.max(180,tb-sy),maxFontSize:getLemeArtMaxFontSize(HAND,d.fontScale),lineHeightRatio:1.3}),old=window.__lemeV1104Color;window.__lemeV1104Color=d.highlightColor||'#52a4d5';drawLemeArtText(ctx,lay,fm.width/2,sy+Math.max(0,(tb-sy-lay.height)/2),{color:'#f4f4f4',align:'center',circleColor:d.highlightColor||'#52a4d5',highlightColor:d.highlightColor||'#52a4d5',underlineColor:'#f4f4f4'});window.__lemeV1104Color=old;const two=String(d.handwrittenMediaMode||'')==='two',imgs=await Promise.all([getLemeArtUserImage(d,'primary').catch(()=>null),two?getLemeArtUserImage(d,'secondary').catch(()=>null):Promise.resolve(null)]);if(two){const gap=26,lw=Math.floor((cw-gap)/2),rw=cw-gap-lw;if(imgs[0])drawLemeArtImageCover(ctx,imgs[0],sx,iy,lw,ih,30);if(imgs[1])drawLemeArtImageCover(ctx,imgs[1],sx+lw+gap,iy,rw,ih,30)}else if(imgs[0])drawLemeArtImageCover(ctx,imgs[0],sx,iy,cw,ih,34);try{const logo=await darkLogo(),w=Math.min(184,fm.width-120),h=Math.round(w*(logo.naturalHeight||logo.height||1)/Math.max(1,logo.naturalWidth||logo.width||1));ctx.drawImage(logo,(fm.width-w)/2,Math.max(0,fm.height-60-h),w,h)}catch{}return canvas}
  const r0=renderLemeArtDraftCanvas;renderLemeArtDraftCanvas=async function(d,f=d?.format,c=null){d=enhance(d||{});const canvas=await r0(d,f,c),s=state(d);return canvas&&s.group==='handwritten'&&s.media>0&&s.dark?darkHand(d,f,canvas):canvas};window.renderLemeArtDraftCanvas=renderLemeArtDraftCanvas;
  window.__LEME_ART_EDITOR_GROUP_VERSION__=V;
})();