import crypto from 'node:crypto';
import dns from 'node:dns/promises';
import net from 'node:net';
import multer from 'multer';

const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024,files:1}});
const ok=(data={})=>({ok:true,...data});
const fail=(message,status=400,code='')=>{const error=new Error(message);error.status=status;error.code=code;throw error;};
const json=value=>value&&typeof value==='object'?value:{};

function instagramUrl(value=''){
  let parsed;try{parsed=new URL(String(value||'').trim());}catch{fail('Informe um link válido da publicação no Instagram.');}
  if(parsed.hostname.toLowerCase().replace(/^www\./,'')!=='instagram.com'||!/^\/(p|reel|reels)\/[A-Za-z0-9_-]+\/?$/i.test(parsed.pathname))fail('Use um link de publicação ou Reel do Instagram.');
  return 'https://www.instagram.com'+parsed.pathname.replace(/\/+$/,'')+'/';
}
function imageInfo(buffer,mime=''){
  if(!Buffer.isBuffer(buffer)||buffer.length<24)return null;
  if(mime==='image/png'&&buffer.toString('ascii',1,4)==='PNG')return {width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};
  if(mime==='image/jpeg'&&buffer[0]===255&&buffer[1]===216){let offset=2;while(offset+9<buffer.length){if(buffer[offset]!==255){offset++;continue;}const marker=buffer[offset+1],size=buffer.readUInt16BE(offset+2);if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(marker))return {height:buffer.readUInt16BE(offset+5),width:buffer.readUInt16BE(offset+7)};if(size<2)break;offset+=2+size;}}
  if(mime==='image/webp'&&buffer.toString('ascii',0,4)==='RIFF'&&buffer.toString('ascii',8,12)==='WEBP'){const type=buffer.toString('ascii',12,16);if(type==='VP8X'&&buffer.length>=30)return {width:1+buffer.readUIntLE(24,3),height:1+buffer.readUIntLE(27,3)};if(type==='VP8 '&&buffer.length>=30)return {width:buffer.readUInt16LE(26)&16383,height:buffer.readUInt16LE(28)&16383};}
  return null;
}
function privateIp(address=''){
  const value=String(address).toLowerCase().replace(/^::ffff:/,'');
  if(net.isIP(value)===4)return /^0\.|^10\.|^127\.|^169\.254\.|^192\.168\.|^172\.(1[6-9]|2\d|3[01])\.|^100\.(6[4-9]|[789]\d|1[01]\d|12[0-7])\.|^198\.(1[89])\.|^(22[4-9]|23\d|24\d|25[0-5])\./.test(value);
  if(net.isIP(value)===6)return value==='::'||value==='::1'||/^f[cd]/.test(value)||/^fe[89ab]/.test(value);
  return true;
}
async function publicTarget(normalizeSiteUrl,url){const parsed=new URL(normalizeSiteUrl(url));const records=await dns.lookup(parsed.hostname,{all:true,verbatim:true}).catch(()=>[]);if(!records.length)fail('O domínio do site não pôde ser localizado.',502,'dns_failed');if(records.some(item=>privateIp(item.address)))fail('O domínio aponta para uma rede não permitida.',400,'private_network');return parsed;}

function defaults(){return {eyebrow:'INSTAGRAM',title:'Acompanhe nossas publicações.',description:'Conteúdos, orientações e novidades.',instagram_username:'',profile_url:'',show_profile_button:true,profile_button_text:'Ver perfil no Instagram',show_card_button:true,card_button_text:'Ver no Instagram',card_button_position:'left',card_button_translucent:false,max_posts:6,columns_desktop:3,columns_tablet:2,columns_mobile:2,gap:20,radius:10,button_style:'solid',animations:true,appearance_mode:'automatic',colors:{background:'#f7f5f2',title:'#1c2b34',text:'#586771',primary:'#2f8fc0',button:'#2f8fc0',button_text:'#ffffff'},fonts:{title:'inherit',body:'inherit'}};}
function config(value={}){
  const base=defaults(),input=json(value),colors=json(input.colors),fonts=json(input.fonts),color=(v,f)=>/^#[0-9a-f]{6}$/i.test(String(v||''))?String(v):f,font=v=>String(v||'inherit').replace(/[^a-z0-9 ,.'"_-]/gi,'').slice(0,100)||'inherit';
  let profile='';if(input.profile_url){try{const u=new URL(input.profile_url);if(u.hostname.toLowerCase().replace(/^www\./,'')==='instagram.com')profile='https://www.instagram.com'+u.pathname.replace(/\/+$/,'')+'/';}catch{}}
  return {eyebrow:String(input.eyebrow??base.eyebrow).trim().slice(0,80),title:String(input.title??base.title).trim().slice(0,180),description:String(input.description??base.description).trim().slice(0,500),instagram_username:String(input.instagram_username||'').replace(/^@/,'').replace(/[^a-z0-9._]/gi,'').slice(0,30),profile_url:profile,show_profile_button:input.show_profile_button!==false,profile_button_text:String(input.profile_button_text??base.profile_button_text).trim().slice(0,100),show_card_button:input.show_card_button!==false,card_button_text:String(input.card_button_text??base.card_button_text).trim().slice(0,80),card_button_position:input.card_button_position==='right'?'right':'left',card_button_translucent:input.card_button_translucent===true,max_posts:Math.min(24,Math.max(1,Number(input.max_posts||6))),columns_desktop:Math.min(4,Math.max(1,Number(input.columns_desktop||3))),columns_tablet:Math.min(3,Math.max(1,Number(input.columns_tablet||2))),columns_mobile:Math.min(2,Math.max(1,Number(input.columns_mobile||2))),gap:Math.min(48,Math.max(0,Number(input.gap??20))),radius:Math.min(40,Math.max(0,Number(input.radius??10))),button_style:['solid','outline','minimal'].includes(input.button_style)?input.button_style:'solid',animations:input.animations!==false,appearance_mode:input.appearance_mode==='custom'?'custom':'automatic',colors:{background:color(colors.background,base.colors.background),title:color(colors.title,base.colors.title),text:color(colors.text,base.colors.text),primary:color(colors.primary,base.colors.primary),button:color(colors.button,base.colors.button),button_text:color(colors.button_text,base.colors.button_text)},fonts:{title:font(fonts.title),body:font(fonts.body)}};
}

export function registerSocialFeed(app,deps){
  const {query,pool,getClientRow,getClientIntegration,normalizeSiteUrl,encryptIntegrationSecret,decryptIntegrationSecret,maskIntegrationSecret,normalizeSubmittedIntegrationSecret,fetchWithTimeout,broadcastRealtime}=deps;
  async function tables(){
    await query("CREATE TABLE IF NOT EXISTS client_sites (id text PRIMARY KEY,client_id text NOT NULL REFERENCES clientes(registro_id) ON DELETE CASCADE,site_url text NOT NULL DEFAULT '',name text NOT NULL DEFAULT 'Site principal',connection_key_encrypted text NOT NULL DEFAULT '',installation_id text NOT NULL DEFAULT '',plugin_version text NOT NULL DEFAULT '',connection_status text NOT NULL DEFAULT 'not_configured',connection_message text NOT NULL DEFAULT '',last_connected_at timestamptz,last_synced_at timestamptz,draft_version integer NOT NULL DEFAULT 1,published_version integer NOT NULL DEFAULT 0,feed_config jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(client_id,site_url))");
    await query("CREATE TABLE IF NOT EXISTS site_feed_posts (id text PRIMARY KEY,site_id text NOT NULL REFERENCES client_sites(id) ON DELETE CASCADE,instagram_url text NOT NULL,alt_text text NOT NULL DEFAULT '',status text NOT NULL DEFAULT 'active',sort_order integer NOT NULL DEFAULT 0,image_data bytea NOT NULL,mime_type text NOT NULL,original_name text NOT NULL DEFAULT '',image_width integer NOT NULL DEFAULT 0,image_height integer NOT NULL DEFAULT 0,crop_x numeric(5,2) NOT NULL DEFAULT 50,crop_y numeric(5,2) NOT NULL DEFAULT 50,content_hash text NOT NULL,draft_version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(site_id,content_hash,instagram_url))");
    await query("CREATE TABLE IF NOT EXISTS site_feed_sync_logs (id text PRIMARY KEY,site_id text NOT NULL REFERENCES client_sites(id) ON DELETE CASCADE,request_id text NOT NULL,version integer NOT NULL,status text NOT NULL,error_code text NOT NULL DEFAULT '',message text NOT NULL DEFAULT '',response jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(site_id,request_id))");
    await query('CREATE INDEX IF NOT EXISTS idx_client_sites_client ON client_sites(client_id,updated_at DESC)');await query('CREATE INDEX IF NOT EXISTS idx_site_feed_posts_site_order ON site_feed_posts(site_id,sort_order,created_at)');
  }
  const expose=(row,counts={})=>{if(!row)return null;const key=decryptIntegrationSecret(row.connection_key_encrypted||'');return {id:row.id,client_id:row.client_id,name:row.name,site_url:row.site_url,has_connection_key:Boolean(key),connection_key_masked:maskIntegrationSecret(key),installation_id:row.installation_id||'',plugin_version:row.plugin_version||'',connection_status:row.connection_status||'not_configured',connection_message:row.connection_message||'',last_connected_at:row.last_connected_at||null,last_synced_at:row.last_synced_at||null,draft_version:Number(row.draft_version||1),published_version:Number(row.published_version||0),has_pending_changes:Number(row.draft_version||1)>Number(row.published_version||0),feed_config:config(row.feed_config),active_posts:Number(counts.active_posts||0),hidden_posts:Number(counts.hidden_posts||0),updated_at:row.updated_at};};
  async function site(clientId,siteId='',create=false){await tables();await getClientRow(clientId);let found=siteId?await query('SELECT * FROM client_sites WHERE id=$1 AND client_id=$2 LIMIT 1',[siteId,clientId]):await query('SELECT * FROM client_sites WHERE client_id=$1 ORDER BY created_at LIMIT 1',[clientId]);if(!found.rows[0]&&create){const old=await getClientIntegration(clientId,false),id='site_'+crypto.randomUUID();found=await query("INSERT INTO client_sites (id,client_id,site_url,feed_config) VALUES ($1,$2,$3,$4::jsonb) RETURNING *",[id,clientId,old?.site_url||'',JSON.stringify(defaults())]);}return found.rows[0]||null;}
  async function bundle(clientId,siteId=''){const current=await site(clientId,siteId,false);if(!current)return {site:null,posts:[],sync_history:[]};const [posts,counts,history]=await Promise.all([query("SELECT id,site_id,instagram_url,alt_text,status,sort_order,mime_type,original_name,image_width,image_height,crop_x,crop_y,content_hash,draft_version,created_at,updated_at FROM site_feed_posts WHERE site_id=$1 ORDER BY sort_order,created_at",[current.id]),query("SELECT COUNT(*) FILTER (WHERE status='active')::int active_posts,COUNT(*) FILTER (WHERE status='hidden')::int hidden_posts FROM site_feed_posts WHERE site_id=$1",[current.id]),query('SELECT id,request_id,version,status,error_code,message,created_at FROM site_feed_sync_logs WHERE site_id=$1 ORDER BY created_at DESC LIMIT 15',[current.id])]);return {site:expose(current,counts.rows[0]),posts:posts.rows.map(post=>({...post,crop_x:Number(post.crop_x),crop_y:Number(post.crop_y),image_url:'/api/clients/'+encodeURIComponent(clientId)+'/sites/'+encodeURIComponent(current.id)+'/feed/posts/'+encodeURIComponent(post.id)+'/image?v='+post.content_hash.slice(0,12)})),sync_history:history.rows};}
  async function wp(current,endpoint,{method='GET',body=null,file=null}={}){const base=normalizeSiteUrl(current.site_url),key=decryptIntegrationSecret(current.connection_key_encrypted);if(!base||!key)fail('Cadastre a URL e a chave do plugin LEME Social Feed.',409,'not_configured');await publicTarget(normalizeSiteUrl,base);const path='/wp-json/leme-social/v1/'+String(endpoint).replace(/^\/+/,''),pretty=new URL(base+path),fallback=new URL(base+'/');fallback.searchParams.set('rest_route',path.replace(/^\/wp-json/,''));let response,payload,lastError;for(const [index,url] of [pretty,fallback].entries()){try{const headers={'X-LEME-KEY':key,Accept:'application/json','User-Agent':'Sistema-LEME/112.42'};let requestBody;if(file){const form=new FormData();form.append('file',new Blob([file.buffer],{type:file.mime}),file.name);form.append('content_hash',file.hash);form.append('external_id',file.externalId);requestBody=form;}else if(body!==null){headers['Content-Type']='application/json';requestBody=JSON.stringify(body);}const candidate=await fetchWithTimeout(url,{method,headers,body:requestBody,redirect:'error'},45000),data=await candidate.json().catch(()=>({}));if(candidate.status===404&&index===0)continue;response=candidate;payload=data;break;}catch(error){lastError=error;}}if(!response)fail(lastError?.name==='AbortError'?'O WordPress demorou para responder.':'Não foi possível acessar o plugin no WordPress.',502,'wordpress_unavailable');if(!response.ok||payload?.success===false){const remoteAuth=[401,403].includes(response.status);fail(payload?.message||payload?.error||payload?.data?.message||(remoteAuth?'A chave do plugin foi recusada. Gere ou copie novamente a chave no WordPress, salve em Configurações do site e teste a conexão.':'O WordPress recusou a sincronização.'),502,payload?.code||payload?.data?.code||(remoteAuth?'wordpress_key_rejected':'wordpress_rejected'));}return payload?.data??payload;}
  async function bump(current,status='pending_changes'){const version=Number(current.draft_version||1)+1;await query('UPDATE client_sites SET draft_version=$2,connection_status=$3,updated_at=now() WHERE id=$1',[current.id,version,status]);return version;}

  app.get('/api/clients/:clientId/sites',async(req,res)=>{await tables();await getClientRow(req.params.clientId);const rows=await query("SELECT s.*,COUNT(p.id) FILTER (WHERE p.status='active')::int active_posts,COUNT(p.id) FILTER (WHERE p.status='hidden')::int hidden_posts FROM client_sites s LEFT JOIN site_feed_posts p ON p.site_id=s.id WHERE s.client_id=$1 GROUP BY s.id ORDER BY s.created_at",[req.params.clientId]);res.json(ok({sites:rows.rows.map(row=>expose(row,row))}));});
  app.get('/api/clients/:clientId/site-social-feed',async(req,res)=>res.json(ok(await bundle(String(req.params.clientId),String(req.query.site_id||'')))));
  app.put('/api/clients/:clientId/site-social-feed/connection',async(req,res)=>{const clientId=String(req.params.clientId),body=json(req.body),current=await site(clientId,String(body.site_id||''),true),url=normalizeSiteUrl(body.site_url??current.site_url??'');let encrypted=current.connection_key_encrypted||'';const key=normalizeSubmittedIntegrationSecret(body.connection_key||'');if(key)encrypted=encryptIntegrationSecret(key);if(body.clear_connection_key===true)encrypted='';const changed=url!==current.site_url||Boolean(key)||body.clear_connection_key===true,saved=await query("UPDATE client_sites SET site_url=$2,name=$3,connection_key_encrypted=$4,connection_status=CASE WHEN $5 THEN CASE WHEN $2='' OR $4='' THEN 'not_configured' ELSE 'pending' END ELSE connection_status END,connection_message=CASE WHEN $5 THEN '' ELSE connection_message END,updated_at=now() WHERE id=$1 RETURNING *",[current.id,url,String(body.name||current.name||'Site principal').slice(0,120),encrypted,changed]);broadcastRealtime('client_sites','updated',current.id,{client_id:clientId});res.json(ok({site:expose(saved.rows[0])}));});
  app.post('/api/clients/:clientId/site-social-feed/test',async(req,res)=>{const clientId=String(req.params.clientId),current=await site(clientId,String(json(req.body).site_id||''),false);if(!current)fail('Configure o site deste cliente.',409);await query("UPDATE client_sites SET connection_status='syncing',connection_message='',updated_at=now() WHERE id=$1",[current.id]);try{const status=await wp(current,'status'),saved=await query("UPDATE client_sites SET connection_status='connected',connection_message='',installation_id=$2,plugin_version=$3,last_connected_at=now(),updated_at=now() WHERE id=$1 RETURNING *",[current.id,String(status.installation_id||''),String(status.version||'')]);res.json(ok({status,site:expose(saved.rows[0])}));}catch(error){await query("UPDATE client_sites SET connection_status='error',connection_message=$2,updated_at=now() WHERE id=$1",[current.id,String(error.message).slice(0,500)]);throw error;}});
  app.get('/api/clients/:clientId/sites/:siteId/feed/posts/:postId/image',async(req,res)=>{const found=await query('SELECT p.image_data,p.mime_type,p.content_hash FROM site_feed_posts p JOIN client_sites s ON s.id=p.site_id WHERE p.id=$1 AND p.site_id=$2 AND s.client_id=$3 LIMIT 1',[req.params.postId,req.params.siteId,req.params.clientId]);if(!found.rows[0])fail('Imagem não encontrada.',404);res.setHeader('Content-Type',found.rows[0].mime_type);res.setHeader('Cache-Control','private,max-age=86400');res.setHeader('ETag','"'+found.rows[0].content_hash+'"');res.send(found.rows[0].image_data);});
  app.post('/api/clients/:clientId/sites/:siteId/feed/posts',upload.single('image'),async(req,res)=>{const clientId=String(req.params.clientId),current=await site(clientId,String(req.params.siteId),false);if(!current)fail('Site não encontrado.',404);if(!req.file)fail('Selecione uma imagem JPG, PNG ou WebP.');if(!['image/jpeg','image/png','image/webp'].includes(req.file.mimetype))fail('Formato inválido. Envie JPG, PNG ou WebP.');const info=imageInfo(req.file.buffer,req.file.mimetype);if(!info?.width||!info?.height)fail('Não foi possível validar a imagem.');if(info.width<320||info.height<400)fail('A imagem precisa ter pelo menos 320 × 400 pixels.');const hash=crypto.createHash('sha256').update(req.file.buffer).digest('hex'),id='feed_'+crypto.randomUUID(),order=Number((await query('SELECT COALESCE(MAX(sort_order),-1)+1 value FROM site_feed_posts WHERE site_id=$1',[current.id])).rows[0].value),version=await bump(current);try{await query("INSERT INTO site_feed_posts (id,site_id,instagram_url,alt_text,status,sort_order,image_data,mime_type,original_name,image_width,image_height,crop_x,crop_y,content_hash,draft_version) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)",[id,current.id,instagramUrl(req.body.instagram_url),String(req.body.alt_text||'').trim().slice(0,500),req.body.status==='hidden'?'hidden':'active',order,req.file.buffer,req.file.mimetype,String(req.file.originalname||'imagem').slice(0,240),info.width,info.height,Math.min(100,Math.max(0,Number(req.body.crop_x??50))),Math.min(100,Math.max(0,Number(req.body.crop_y??50))),hash,version]);}catch(error){if(error.code==='23505')fail('Esta mesma imagem e link já estão cadastrados.',409);throw error;}broadcastRealtime('site_feed_posts','created',id,{client_id:clientId,site_id:current.id});res.status(201).json(ok(await bundle(clientId,current.id)));});
  app.put('/api/clients/:clientId/sites/:siteId/feed/posts/:postId',upload.single('image'),async(req,res)=>{const clientId=String(req.params.clientId),current=await site(clientId,String(req.params.siteId),false);if(!current)fail('Site não encontrado.',404);const found=(await query('SELECT * FROM site_feed_posts WHERE id=$1 AND site_id=$2',[req.params.postId,current.id])).rows[0];if(!found)fail('Publicação não encontrada.',404);let buffer=found.image_data,mime=found.mime_type,name=found.original_name,width=found.image_width,height=found.image_height,hash=found.content_hash;if(req.file){if(!['image/jpeg','image/png','image/webp'].includes(req.file.mimetype))fail('Formato inválido.');const info=imageInfo(req.file.buffer,req.file.mimetype);if(!info)fail('Imagem inválida.');buffer=req.file.buffer;mime=req.file.mimetype;name=req.file.originalname;width=info.width;height=info.height;hash=crypto.createHash('sha256').update(buffer).digest('hex');}const version=await bump(current);await query("UPDATE site_feed_posts SET instagram_url=$3,alt_text=$4,status=$5,image_data=$6,mime_type=$7,original_name=$8,image_width=$9,image_height=$10,crop_x=$11,crop_y=$12,content_hash=$13,draft_version=$14,updated_at=now() WHERE id=$1 AND site_id=$2",[found.id,current.id,instagramUrl(req.body.instagram_url??found.instagram_url),String(req.body.alt_text??found.alt_text).trim().slice(0,500),req.body.status==='hidden'?'hidden':'active',buffer,mime,String(name).slice(0,240),width,height,Math.min(100,Math.max(0,Number(req.body.crop_x??found.crop_x))),Math.min(100,Math.max(0,Number(req.body.crop_y??found.crop_y))),hash,version]);res.json(ok(await bundle(clientId,current.id)));});
  app.delete('/api/clients/:clientId/sites/:siteId/feed/posts/:postId',async(req,res)=>{const current=await site(String(req.params.clientId),String(req.params.siteId),false);if(!current)fail('Site não encontrado.',404);const removed=await query('DELETE FROM site_feed_posts WHERE id=$1 AND site_id=$2 RETURNING id',[req.params.postId,current.id]);if(!removed.rows[0])fail('Publicação não encontrada.',404);await bump(current);res.json(ok(await bundle(req.params.clientId,current.id)));});
  app.put('/api/clients/:clientId/sites/:siteId/feed/order',async(req,res)=>{const current=await site(String(req.params.clientId),String(req.params.siteId),false);if(!current)fail('Site não encontrado.',404);const ids=Array.isArray(req.body.ids)?req.body.ids.map(String):[],existing=(await query('SELECT id FROM site_feed_posts WHERE site_id=$1',[current.id])).rows.map(row=>row.id);if(ids.length!==existing.length||ids.some(id=>!existing.includes(id)))fail('A ordem não corresponde às publicações deste site.');const client=await pool.connect();try{await client.query('BEGIN');for(let i=0;i<ids.length;i++)await client.query('UPDATE site_feed_posts SET sort_order=$3,updated_at=now() WHERE id=$1 AND site_id=$2',[ids[i],current.id,i]);await client.query("UPDATE client_sites SET draft_version=draft_version+1,connection_status='pending_changes',updated_at=now() WHERE id=$1",[current.id]);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}res.json(ok(await bundle(req.params.clientId,current.id)));});
  app.put('/api/clients/:clientId/sites/:siteId/feed/config',async(req,res)=>{const current=await site(String(req.params.clientId),String(req.params.siteId),false);if(!current)fail('Site não encontrado.',404);await query("UPDATE client_sites SET feed_config=$2::jsonb,draft_version=draft_version+1,connection_status='pending_changes',updated_at=now() WHERE id=$1",[current.id,JSON.stringify(config(req.body))]);res.json(ok(await bundle(req.params.clientId,current.id)));});
  app.post('/api/clients/:clientId/sites/:siteId/feed/publish',async(req,res)=>{const clientId=String(req.params.clientId),current=await site(clientId,String(req.params.siteId),false);if(!current)fail('Site não encontrado.',404);const posts=(await query("SELECT * FROM site_feed_posts WHERE site_id=$1 AND status='active' ORDER BY sort_order,created_at",[current.id])).rows,version=Number(current.draft_version),requestId='sync_'+current.id+'_'+version,previous=(await query('SELECT * FROM site_feed_sync_logs WHERE site_id=$1 AND request_id=$2',[current.id,requestId])).rows[0];if(previous?.status==='success')return res.json(ok({idempotent:true,...await bundle(clientId,current.id)}));await query("INSERT INTO site_feed_sync_logs (id,site_id,request_id,version,status,message) VALUES ($1,$2,$3,$4,'processing','Sincronização iniciada.') ON CONFLICT (site_id,request_id) DO UPDATE SET status='processing',error_code='',message='Nova tentativa iniciada.',created_at=now()",['log_'+crypto.randomUUID(),current.id,requestId,version]);await query("UPDATE client_sites SET connection_status='syncing',connection_message='' WHERE id=$1",[current.id]);try{const media=[];for(const post of posts){const uploaded=await wp(current,'media',{method:'POST',file:{buffer:post.image_data,mime:post.mime_type,name:post.original_name||'instagram',hash:post.content_hash,externalId:post.id}});media.push({id:post.id,attachment_id:Number(uploaded.attachment_id),image_url:String(uploaded.url||''),instagram_url:post.instagram_url,alt_text:post.alt_text,sort_order:post.sort_order,crop_x:Number(post.crop_x),crop_y:Number(post.crop_y),content_hash:post.content_hash});}const result=await wp(current,'feed',{method:'PUT',body:{request_id:requestId,version,config:config(current.feed_config),posts:media}});await query("UPDATE client_sites SET published_version=$2,connection_status='synced',connection_message='',installation_id=COALESCE(NULLIF($3,''),installation_id),plugin_version=COALESCE(NULLIF($4,''),plugin_version),last_connected_at=now(),last_synced_at=now(),updated_at=now() WHERE id=$1",[current.id,version,String(result.installation_id||''),String(result.version||'')]);await query("UPDATE site_feed_sync_logs SET status='success',message='Feed publicado com sucesso.',response=$3::jsonb WHERE site_id=$1 AND request_id=$2",[current.id,requestId,JSON.stringify(result)]);broadcastRealtime('client_sites','synced',current.id,{client_id:clientId,version});res.json(ok({published:true,...await bundle(clientId,current.id)}));}catch(error){await query("UPDATE client_sites SET connection_status='error',connection_message=$2,updated_at=now() WHERE id=$1",[current.id,String(error.message).slice(0,500)]);await query("UPDATE site_feed_sync_logs SET status='failed',error_code=$3,message=$4 WHERE site_id=$1 AND request_id=$2",[current.id,requestId,String(error.code||'sync_failed'),String(error.message).slice(0,500)]);throw error;}});
}
